name: transformer_eeg
channels:
  - pytorch
  - conda-forge/label/cf202003
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - anyio=2.0.2=py38h578d9bd_4
  - argon2-cffi=20.1.0=py38h25fe258_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.4=py38h261ae71_0
  - chardet=4.0.0=py38h06a4308_1003
  - conda-package-handling=1.7.2=py38h03888b9_0
  - cryptography=3.3.1=py38h3c74f83_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=3.4.0=py38h578d9bd_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - intel-openmp=2020.2=254
  - ipykernel=5.4.2=py38h81c977d_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.2=py38_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.0=py38h578d9bd_0
  - jupyter_server=1.2.2=py38h578d9bd_1
  - jupyterlab=3.0.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.1.2=pyhd8ed1ab_0
  - jupyterthemes=0.20.0=py_1
  - kiwisolver=1.3.0=py38h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lesscpy=0.13.0=py_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markupsafe=1.1.1=py38h8df0ef7_2
  - matplotlib=3.3.2=h06a4308_0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mistune=0.8.4=py38h25fe258_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - ninja=1.10.2=py38hff7bd54_0
  - nodejs=12.4.0=he1b5a44_0
  - notebook=6.2.0=py38h578d9bd_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.8=pyhd3deb0d_0
  - pandoc=2.11.3.2=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=8.1.0=py38he98fc37_0
  - pip=20.3.3=py38h06a4308_0
  - ply=3.11=py_1
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - ptyprocess=0.6.0=py38_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h25fe258_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.5=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyzmq=19.0.2=py38ha71036d_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.87=py38h7b6447c_1
  - scikit-learn=0.23.2=py38h0573a6f_0
  - send2trash=1.5.0=py_0
  - setuptools=51.3.3=py38h06a4308_4
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sniffio=1.2.0=py38h578d9bd_1
  - soupsieve=2.1=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.2=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.2=py38
  - torchtext=0.8.1=py38
  - torchvision=0.8.2=py38_cu102
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.55.1=pyhd3eb1b0_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.2=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=h58526e2_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - alabaster==0.7.12
    - bdist-wheel-name==0.1.0
    - bs4==0.0.1
    - cachetools==4.2.1
    - click==7.1.2
    - dill==0.3.3
    - docutils==0.16
    - emd-signal==0.2.10
    - et-xmlfile==1.0.1
    - filelock==3.0.12
    - future==0.18.2
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.35.0
    - h5py==3.1.0
    - imagesize==1.2.0
    - ipympl==0.6.2
    - ipywidgets==7.6.3
    - jdcal==1.4.1
    - jupyterlab-widgets==1.0.0
    - lxml==4.6.2
    - markdown==3.3.3
    - mne==0.22.0
    - multiprocess==0.70.11.1
    - nltk==3.5
    - nolds==0.5.2
    - numpydoc==1.1.0
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - openpyxl==3.0.6
    - pandas==1.2.0
    - parso==0.7.1
    - pathos==0.2.7
    - pox==0.2.9
    - ppft==1.6.6.3
    - prompt-toolkit==3.0.10
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - regex==2020.11.13
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - sacremoses==0.0.43
    - scipy==1.6.0
    - seaborn==0.11.1
    - snowballstemmer==2.0.0
    - sphinx==3.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tokenizers==0.10.1
    - transformers==4.3.2
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - xlrd==2.0.1
prefix: /home/vdelv/anaconda3/envs/transformer_eeg
